name: publish-linux-x64

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: |
          dotnet restore ModPackUpdater/ModPackUpdater.csproj

      - name: Publish (linux-x64, self-contained single file)
        run: |
          dotnet publish ModPackUpdater/ModPackUpdater.csproj \
            -c Release \
            -r linux-x64 \
            -f net9.0 \
            --self-contained true \
            /p:PublishSingleFile=true \
            /p:IncludeAllContentForSelfExtract=true \
            /p:EnableCompressionInSingleFile=true \
            /p:DebugType=none \
            /p:GenerateDocumentationFile=false \
            /p:InvariantGlobalization=true

      - name: Upload publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: ModPackUpdater-linux-x64
          path: ModPackUpdater/bin/Release/net9.0/linux-x64/publish/
          if-no-files-found: error

